DROP TABLE IF EXISTS PUBLISHER;

CREATE TABLE PUBLISHER (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  CONSTRAINT PUB_PRIMARY_KEY PRIMARY KEY (id)
);


DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(250) NOT NULL,
  pub_name VARCHAR(250) NOT NULL,
  version VARCHAR(250) NOT NULL,
  CONSTRAINT PRODUCT_PRIMARY_KEY PRIMARY KEY (id),
  CONSTRAINT PUBLISHER_FOREIGN_KEY FOREIGN KEY (pub_name) REFERENCES PUBLISHER (name)
);